# Generated by Django 4.2.1 on 2023-06-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_gene_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneattributelink',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genedata.attribute'),
        ),
        migrations.AlterField(
            model_name='geneattributelink',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genedata.gene'),
        ),
    ]
